services:
  - type: web
    name: smart-planner
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: smart-planner-db
          property: connectionString

databases:
  - name: smart-planner-db
    databaseName: smart_planner
    user: smart_planner_user
